
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
rule_files:
  - rules.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alert-manager:9093
      scheme: http
      timeout: 10s
      api_version: v1

scrape_configs:
 - job_name: prometheus-container
   static_configs:
    - targets:
       - prometheus:9090
  
 - job_name: node-exporter
   static_configs:
    - targets:
       - node:9100
